#TODO

all: 
	gcc -pedantic -std=c99 -Wall -Wextra -lm -o Test ../scanner.c TestScanner.c

test: 	
	gcc -pedantic -std=c99 -Wall -Wextra -lm -o Test ../scanner.c TestScanner.c
	./Test test

clean:
	rm Test


